INFO     conftest:conftest.py:53 Инициализация WebDriver
ERROR    pages.demoqa_page:demoqa_page.py:122 Ошибка при клике на кнопку Elements: HTTPConnectionPool(host='localhost', port=48727): Read timed out. (read timeout=120)
ERROR    test_check_text:test_check_text.py:84 Тест упал с ошибкой: HTTPConnectionPool(host='localhost', port=48727): Read timed out. (read timeout=120)
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=48727): Read timed out. (read timeout=120)")': /session/1d176248842fd57659669f84f245a503/url
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=48727): Read timed out. (read timeout=120)")': /session/1d176248842fd57659669f84f245a503/url
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=48727): Read timed out. (read timeout=120)")': /session/1d176248842fd57659669f84f245a503/url
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=48727): Read timed out. (read timeout=120)")': /session/1d176248842fd57659669f84f245a503
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=48727): Read timed out. (read timeout=120)")': /session/1d176248842fd57659669f84f245a503
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=48727): Read timed out. (read timeout=120)")': /session/1d176248842fd57659669f84f245a503
INFO     conftest:conftest.py:105 Завершение работы WebDriver